project_id = "macrotracker"

[functions.meal-interpretations-text]
verify_jwt = false

[functions.meal-interpretations-photo]
verify_jwt = false

[functions.stripe-pro-webhook]
verify_jwt = false

[functions.stripe-pro-checkout]
verify_jwt = true
