import 'package:flutter/material.dart';

const String fontFamily = 'Poppins';

var appTextTheme = const TextTheme(
  displayLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 93,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  displayMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 58,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  displaySmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 46,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  headlineMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 33,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  headlineSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 23,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  titleLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 19,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  titleMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 15,
      fontWeight: FontWeight.w600,
      letterSpacing: 0),
  titleSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 13,
      fontWeight: FontWeight.w600,
      letterSpacing: 0),
  bodyLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 15,
      fontWeight: FontWeight.w400,
      letterSpacing: 0),
  bodyMedium: TextStyle(
      fontFamily: fontFamily,
      fontSize: 13,
      fontWeight: FontWeight.w400,
      letterSpacing: 0),
  labelLarge: TextStyle(
      fontFamily: fontFamily,
      fontSize: 13,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
  bodySmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0),
  labelSmall: TextStyle(
      fontFamily: fontFamily,
      fontSize: 10,
      fontWeight: FontWeight.w700,
      letterSpacing: 0),
);
